config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :show, :create]
  resource :session, only: [:new, :create, :destroy]

  resources :subs
  resources :posts, except: :index

  root to: 'sessions#new'
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :sub

  belongs_to :author,
    class_name: "User"

  validates :title, :sub_id, :author_id, presence: true 
end

app/models/sub.rb
# == Schema Information
#
# Table name: subs
#
#  id           :integer          not null, primary key
#  title        :string           not null
#  description  :text
#  moderator_id :integer          not null
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Sub < ActiveRecord::Base
  belongs_to :moderator,
    class_name: "User",
    foreign_key: :moderator_id,
    primary_key: :id

  has_many :posts

  validates :title, :moderator_id, presence: true
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  username        :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ActiveRecord::Base
  attr_reader :password

  has_many :subs,
    foreign_key: :moderator_id

  has_many :posts,
    foreign_key: :author_id

  validates :username, :password_digest, :session_token, presence: true
  validates :username, :session_token, uniqueness: true
  validates :password, length: { minimum: 6, allow_nil: true }

  after_initialize :ensure_session_token

  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)
    user && user.is_password?(password) ? user : nil
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(@password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def reset_session_token!
    self.session_token = SecureRandom.urlsafe_base64
    self.save!
    self.session_token
  end

  private
  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def current_user
    return nil unless session[:session_token]
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def login_user!(user)
    session[:session_token] = user.reset_session_token!
  end

  def logout!
    current_user.reset_session_token!
    session[:session_token] = nil
  end

  def logged_in?
    !!current_user
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_author!, only: [:edit, :update, :destroy]

  def new
    @post = Post.new
    @subs = Sub.all
    render :new
  end

  def edit
    @post = Post.find(params[:id])
    render :edit
  end

  def update
    @post = Post.find(params[:id])
    return nil if @post.nil?
    if @post.update(post_params)
      redirect_to post_url(@post)
    else
      flash.now[:notice] = @post.errors.full_messages
      render :edit
    end
  end

  def show
    @post = Post.find(params[:id])
    render :show
  end

  def create
    @post = current_user.posts.new(post_params)
    @subs = Sub.all

    if @post.save
      redirect_to post_url(@post)
    else
      flash.now[:notice] = @post.errors.full_messages
      render :new
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    flash[:notice] = ["#{@post.title deleted}."]
    redirect_to sub_url(@post.sub_id)
  end

  private
  def post_params
    params.require(:post).permit(:title, :url, :content, :sub_id)
  end

  def require_author!
    post = Post.find(params[:id])
    redirect_to post_url(post) unless current_user.id == post.author_id
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    render :new
  end

  def create
    user = User.find_by_credentials(
      params[:user][:username],
      params[:user][:password]
    )

    #Switch branches
    if user.nil?
      flash.now[:notice] = ["Incorrect Username or Password"]
      render :new
    else
      login_user!(user)
      redirect_to user_url(user)
    end
  end

  def destroy
    logout!
    redirect_to root_url
  end
end

app/controllers/subs_controller.rb
class SubsController < ApplicationController
  before_action :require_moderator!, only: [:edit, :update, :destroy]

  def index
    @subs = Sub.all
    render :index
  end

  def show
    @sub = Sub.includes(:posts).find(params[:id])
    @posts = @sub.posts
    
    render :show
  end

  def new
    @sub = Sub.new
    render :new
  end

  def edit
    @sub = Sub.find(params[:id])
    render :edit
  end

  def create
    @sub = current_user.subs.new(sub_params)

    if @sub.save
      redirect_to sub_url(@sub)
    else
      flash.now[:notice] = @sub.errors.full_messages
      render :new
    end
  end

  def update
    @sub = Sub.find(params[:id])
    if @sub.update(sub_params)
      redirect_to sub_url(@sub)
    else
      flash.now[:notice] = @sub.error.full_messages
      render :edit
    end
  end

  def destroy
    @sub = Sub.find(params[:id])
    @sub.destroy
  end

  private
  def sub_params
    params.require(:sub).permit(:title, :description)
  end

  def require_moderator!
    mod_id = Sub.find(params[:id]).moderator_id
    redirect_to subs_url unless current_user.id == mod_id
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    render :show
  end

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      login_user!(@user)
      redirect_to subs_url
    else
      flash.now[:notice] = @user.errors.full_messages
      render :new
    end
  end

  private
  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def auth_token
    html = <<-HTML
      <input type="hidden"
             name="authenticity_token"
             value="#{form_authenticity_token}">
    HTML
    html.html_safe
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/subs_helper.rb
module SubsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Reddit</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render "shared/header" %>
  <%= render "shared/notice" %>

<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<% action = post.persisted? ? post_url(post) : posts_url %>
<% method = post.persisted? ? :patch : :post %>

<form action="<%= action %>" method="post">
  <%= auth_token %>
  <input type="hidden" name="_method" value="<%= method %>">

  <label for="post_title">Title</label>
  <input type="text" name="post[title]" value="<%= post.title %>" id="post_title">
  <br>
  <br>
  <label for="post_link">Link</label>
  <input type="text" name="post[url]" value="<%= post.url %>" id="post_link">
  <br>
  <br>
  <label for="post_content">Content</label>
  <textarea
    name="post[content]"
    id="post_content"><%= post.content %></textarea>
  <br>
  <br>
  <label for="post_sub">Sub</label>
  <select name="post[sub_id]" id="post_sub">
    <option></option>
    <% subs.each do |sub| %>
      <option
        <%= sub.id == post.sub_id ? "selected" : "" %>
        value="<%= sub.id %>">
        <%= sub.title %>
      </option>
    <% end %>
  </select>
  <br>
  <br>
  </select>
  <input type="submit" value="submit">
</form>

app/views/posts/edit.html.erb
<h1>Posts#edit</h1>
<p>Find me in app/views/posts/edit.html.erb</p>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render "form", post: @post, subs: @subs %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>

app/views/shared/_header.html.erb
<% if logged_in? %>
  <%= current_user.username %>
  <%= button_to "Log out", session_url, method: "delete" %>
<% else %>
  <%= button_to "Log in", new_session_url, method: "get" %>
  <%= button_to "Sign up", new_user_url, method: "get" %>
<% end %>

app/views/shared/_notice.html.erb
<% if flash[:notice].is_a?(Array) %>
  <ul>
  <% flash[:notice].each do |notice| %>
    <li><%= notice %></li>
  <% end %>
  </ul>
<% end %>

app/views/shared/_user_input.html.erb
<form action="<%= action %>" method="post">
  <%= auth_token %>
  <label for="user_username">Username</label>
  <input type="text"
         name="user[username]"
         value="<%= user.username unless user.nil? %>"
         id="user_username">
  <br><br>
  <label for="user_password">Password</label>
  <input type="password"
         name="user[password]"
         id="user_password">
  <br><br>
  <input type="submit" value="submit">
</form>

app/views/subs/_form.html.erb
<% action = sub.persisted? ? sub_url(sub) : subs_url %>
<% method = sub.persisted? ? :patch : :post %>

<form action="<%= action %>" method="post">
  <%= auth_token %>
  <input type="hidden" name="_method" value="<%= method %>">

  <label for="sub_title">Title</label>
  <input type="text" name="sub[title]" value="<%= sub.title %>" id="sub_title">
  <br>
  <br>
  <label for="sub_description">Description</label>
  <textarea
    name="sub[description]"
    id="sub_description"><%= sub.description %></textarea>
  <br>
  <br>
  <input type="submit" value="submit">
</form>

app/views/subs/edit.html.erb
<h1>Edit <%= @sub.title %></h1>

<%= render "form", sub: @sub %>

<br><br>
<%= button_to "Delete #{@sub.title}", sub_url(@sub), method: :delete,
  data: { confirm: "Are you sure you want to delete #{@sub.title}?" }%>
<br>
<%= button_to "Back to #{@sub.title}", sub_url(@sub), method: :get %>
<%= button_to "All Subs", subs_url, method: :get %>

app/views/subs/index.html.erb
<h1>Subs</h1>

<ul>
<% @subs.each do |sub| %>
  <li><%= link_to sub.title, sub_url(sub.id) %></li>
<% end %>
</ul>
<br>
<br>
<%= button_to "Create Sub", new_sub_url, method: :get %>

app/views/subs/new.html.erb
<h1>Subs</h1>

<%= render "form", sub: @sub %>

app/views/subs/show.html.erb
<h1><%= @sub.title %></h1>

<%= @sub.description %>

<ul>
<% @posts.each do |post| %>
  <li><%=link_to "#{post.title}", post_url(post)%></li>
<% end %>
</ul>


<br><br>
<%= button_to "Edit #{@sub.title}", edit_sub_url(@sub), method: :get %>
<%= button_to "All subs", subs_url, method: :get %>

app/views/users/new.html.erb
<h1>Sign up!!</h1>

<%= render "shared/user_input", action: users_url, user: @user %>

app/views/users/show.html.erb
<h1><%= @user.username %></h1>